
playable_cast = {
    'Dr. M',
    'Dr. N',
    'Mr. A',
    'Mr. C',
    'Mr. D',
    'Mr. G',
    'Mr. I',
    'Mr. K',
    'Mr. P',
    'Mr. Q',
    'Mr. S',
    'Mr. U',
    'Ms. B',
    'Ms. E',
    'Ms. F',
    'Ms. H',
    'Ms. J',
    'Ms. L',
    'Ms. O',
    'Ms. R',
    'Ms. T'
}
male_cast = {chara for chara in playable_cast if chara[1] == "r"}
female_cast = playable_cast - male_cast

extended_cast = playable_cast | {
    "Toby",
    "Damon"
}

common_nicknames = {
    'Dr. M': "Plain",
    'Dr. N': "Bling",
    'Mr. A': "Disney",
    'Mr. C': "Taft",
    'Mr. D': "Cane",
    'Mr. G': "General",
    'Mr. I': "Wheels",
    'Mr. K': "Sikh",
    'Mr. P': "Tex",
    'Mr. Q': "Salmon",
    'Mr. S': "Smallman",
    'Mr. U': "Duke",
    'Ms. B': "Boots",
    'Ms. E': "Pearls",
    'Ms. F': "Alice",
    'Ms. H': "Hair",
    'Ms. J': "Queen",
    'Ms. L': "Rocker",
    'Ms. O': "Irish",
    'Ms. R': "Teal",
    'Ms. T': "Sari",
    'Damon': "Damon",
    'Toby': "Toby"
}

alt_nicknames = {
    'Dr. M': [],
    'Dr. N': [],
    'Mr. A': [],
    'Mr. C': [],
    'Mr. D': [],
    'Mr. G': ["Colonel"],
    'Mr. I': [],
    'Mr. K': [],
    'Mr. P': ["Cowboy"],
    'Mr. Q': [],
    'Mr. S': [],
    'Mr. U': ["Prince"],
    'Ms. B': ["Buns"],
    'Ms. E': [],
    'Ms. F': ["Jockey", "Ponytail"],
    'Ms. H': ["Red Dress"],
    'Ms. J': [],
    'Ms. L': ["Leopard"],
    'Ms. O': ["Green Dress"],
    'Ms. R': ["Mom"],
    'Ms. T': ["Orange Dress"],
    'Toby': ["Swolby"]
}

lookalike_nicknames = {
    'Dr. M': [],
    'Dr. N': [],
    'Mr. A': ["Walt Disney", "Andrew Ryan"],
    'Mr. C': ["Theodore Roosevelt"],
    'Mr. D': ["Morgan Freeman"],
    'Mr. G': [],
    'Mr. I': ["Austin Powers"],
    'Mr. K': [],
    'Mr. P': [],
    'Mr. Q': ["Mr. Clean"],
    'Mr. S': ["Danny DeVito"],
    'Mr. U': [],
    'Ms. B': ["Irene Adler"],
    'Ms. E': ["Helen Mirren"],
    'Ms. F': [],
    'Ms. H': ["Oprah Winfrey"],
    'Ms. J': ["Queen Elizabeth"],
    'Ms. L': [],
    'Ms. O': [],
    'Ms. R': [],
    'Ms. T': [],
}

internal_nicknames = {
    'Dr. M': "Sam",
    'Dr. N': "Sam",
    'Mr. A': "Bond",
    'Mr. C': "Banker",
    'Mr. D': "Morgan",
    'Mr. G': "General",
    'Mr. I': "Victor",
    'Mr. K': "Samrath",
    'Mr. P': "Salvador",
    'Mr. Q': "Danger",
    'Mr. S': "Dom",
    'Mr. U': "Duke",
    'Ms. B': "Emma",
    'Ms. E': "Beatrice",
    'Ms. F': "Alice",
    'Ms. H': "Michelle",
    'Ms. J': "Clara",
    'Ms. L': "Sibel",
    'Ms. O': "Sofia",
    'Ms. R': "Danielle",
    'Ms. T': "Devi",
}

phonetic_nicknames = {
    'Dr. M': "Max",
    'Dr. N': "Nick",
    'Mr. A': "Andrew",
    'Mr. C': "Calvin",
    'Mr. D': "",
    'Mr. G': "",
    'Mr. I': "Isaac",
    'Mr. K': "",
    'Mr. P': "Pedro",
    'Mr. Q': "",
    'Mr. S': "",
    'Mr. U': "Ulysses",
    'Ms. B': "",
    'Ms. E': "",
    'Ms. F': "",
    'Ms. H': "",
    'Ms. J': "",
    'Ms. L': "",
    'Ms. O': "",
    'Ms. R': "",
    'Ms. T': "",
}

roles = {
    "Spy",
    "SeductionTarget",
    "Ambassador",
    "DoubleAgent",
    "SuspectedDoubleAgent",
    "Civilian",
    "Staff"
}