
all_unique_timeline_events = (
    '45 seconds added to match.',
    'aborted watch check to add time.',
    'action test canceled: contact double agent',
    'action test canceled: purloin guest list',
    'action test canceled: seduce target',
    'action test green: check watch',
    'action test green: contact double agent',
    'action test green: fingerprint ambassador',
    'action test green: inspect statues',
    'action test green: purloin guest list',
    'action test green: seduce target',
    'action test green: swap statue',
    'action test green: transfer microfilm',
    'action test ignored: check watch',
    'action test ignored: contact double agent',
    'action test ignored: fingerprint ambassador',
    'action test ignored: inspect statues',
    'action test ignored: purloin guest list',
    'action test ignored: seduce target',
    'action test ignored: swap statue',
    'action test ignored: transfer microfilm',
    'action test red: check watch',
    'action test red: contact double agent',
    'action test red: fingerprint ambassador',
    'action test red: inspect statues',
    'action test red: purloin guest list',
    'action test red: seduce target',
    'action test red: swap statue',
    'action test red: transfer microfilm',
    'action test white: check watch',
    'action test white: contact double agent',
    'action test white: inspect statues',
    'action test white: purloin guest list',
    'action test white: seduce target',
    'action test white: swap statue',
    'action test white: transfer microfilm',
    'action triggered: bug ambassador',
    'action triggered: check watch',
    'action triggered: contact double agent',
    'action triggered: fingerprint ambassador',
    'action triggered: inspect statues',
    'action triggered: purloin guest list',
    'action triggered: seduce target',
    'action triggered: swap statue',
    'action triggered: transfer microfilm',
    'all statues inspected.',
    'ambassador cast.',
    'ambassador\'s personal space violated.',
    'banana bread aborted.',
    'banana bread uttered.',
    'bartender offered cupcake.',
    'bartender offered drink.',
    'bartender picked next customer.',
    'begin flirtation with seduction target.',
    'begin planting bug while standing.',
    'begin planting bug while walking.',
    'bit cupcake.',
    'bug ambassador enabled.',
    'bug ambassador selected.',
    'bug transitioned from standing to walking.',
    'bugged ambassador while standing.',
    'bugged ambassador while walking.',
    'cast member picked up pending statue.',
    'character picked up pending statue.',
    'chomped cupcake.',
    'civilian cast.',
    'contact double agent enabled.',
    'contact double agent selected.',
    'delegated purloin timer expired.',
    'delegated purloin to dr. m.',
    'delegated purloin to dr. n.',
    'delegated purloin to mr. a.',
    'delegated purloin to mr. c.',
    'delegated purloin to mr. d.',
    'delegated purloin to mr. g.',
    'delegated purloin to mr. i.',
    'delegated purloin to mr. k.',
    'delegated purloin to mr. p.',
    'delegated purloin to mr. q.',
    'delegated purloin to mr. s.',
    'delegated purloin to mr. u.',
    'delegated purloin to ms. b.',
    'delegated purloin to ms. e.',
    'delegated purloin to ms. f.',
    'delegated purloin to ms. h.',
    'delegated purloin to ms. j.',
    'delegated purloin to ms. l.',
    'delegated purloin to ms. o.',
    'delegated purloin to ms. r.',
    'delegated purloin to ms. t.',
    'delegating purloin guest list.',
    'demand drink from bartender.',
    'double agent cast.',
    'double agent contacted.',
    'double agent joined conversation with spy.',
    'double agent left conversation with spy.',
    'dropped statue.',
    'failed flirt with seduction target.',
    'failed planting bug while walking.',
    'fake banana bread started.',
    'fake banana bread uttered.',
    'fingerprint ambassador enabled.',
    'fingerprint ambassador selected.',
    'fingerprinted ambassador.',
    'fingerprinted book.',
    'fingerprinted briefcase.',
    'fingerprinted cupcake.',
    'fingerprinted drink.',
    'fingerprinted statue.',
    'fingerprinting failed.',
    'flirt with seduction target: 100%',
    'flirt with seduction target: 17%',
    'flirt with seduction target: 18%',
    'flirt with seduction target: 19%',
    'flirt with seduction target: 20%',
    'flirt with seduction target: 21%',
    'flirt with seduction target: 22%',
    'flirt with seduction target: 23%',
    'flirt with seduction target: 24%',
    'flirt with seduction target: 25%',
    'flirt with seduction target: 26%',
    'flirt with seduction target: 27%',
    'flirt with seduction target: 28%',
    'flirt with seduction target: 29%',
    'flirt with seduction target: 30%',
    'flirt with seduction target: 31%',
    'flirt with seduction target: 32%',
    'flirt with seduction target: 33%',
    'flirt with seduction target: 34%',
    'flirt with seduction target: 35%',
    'flirt with seduction target: 36%',
    'flirt with seduction target: 37%',
    'flirt with seduction target: 38%',
    'flirt with seduction target: 39%',
    'flirt with seduction target: 40%',
    'flirt with seduction target: 41%',
    'flirt with seduction target: 42%',
    'flirt with seduction target: 43%',
    'flirt with seduction target: 44%',
    'flirt with seduction target: 45%',
    'flirt with seduction target: 46%',
    'flirt with seduction target: 47%',
    'flirt with seduction target: 48%',
    'flirt with seduction target: 49%',
    'flirt with seduction target: 50%',
    'flirt with seduction target: 51%',
    'flirt with seduction target: 52%',
    'flirt with seduction target: 53%',
    'flirt with seduction target: 54%',
    'flirt with seduction target: 55%',
    'flirt with seduction target: 56%',
    'flirt with seduction target: 57%',
    'flirt with seduction target: 58%',
    'flirt with seduction target: 59%',
    'flirt with seduction target: 60%',
    'flirt with seduction target: 61%',
    'flirt with seduction target: 62%',
    'flirt with seduction target: 63%',
    'flirt with seduction target: 64%',
    'flirt with seduction target: 65%',
    'flirt with seduction target: 66%',
    'flirt with seduction target: 67%',
    'flirt with seduction target: 68%',
    'flirt with seduction target: 69%',
    'flirt with seduction target: 70%',
    'flirt with seduction target: 71%',
    'flirt with seduction target: 72%',
    'flirt with seduction target: 73%',
    'flirt with seduction target: 74%',
    'flirt with seduction target: 75%',
    'flirt with seduction target: 76%',
    'flirt with seduction target: 77%',
    'flirt with seduction target: 78%',
    'flirt with seduction target: 79%',
    'flirt with seduction target: 80%',
    'flirt with seduction target: 81%',
    'flirt with seduction target: 82%',
    'flirt with seduction target: 83%',
    'flirt with seduction target: 84%',
    'flirt with seduction target: 85%',
    'flirt with seduction target: 86%',
    'flirt with seduction target: 87%',
    'flirt with seduction target: 88%',
    'flirt with seduction target: 89%',
    'flirt with seduction target: 90%',
    'flirt with seduction target: 91%',
    'flirt with seduction target: 92%',
    'flirt with seduction target: 93%',
    'flirt with seduction target: 94%',
    'flirt with seduction target: 95%',
    'flirt with seduction target: 96%',
    'flirt with seduction target: 97%',
    'flirt with seduction target: 98%',
    'flirt with seduction target: 99%',
    'flirtation cooldown expired.',
    'game started.',
    'get book from bookcase.',
    'got cupcake from bartender.',
    'got cupcake from waiter.',
    'got drink from bartender.',
    'got drink from waiter.',
    'guest list purloin pending.',
    'guest list purloined.',
    'guest list return pending.',
    'guest list returned.',
    'gulped drink.',
    'held statue inspected.',
    'hide microfilm in book.',
    'inspect 1 statue enabled.',
    'inspect 1 statue selected.',
    'inspect 2 statues enabled.',
    'inspect 2 statues selected.',
    'inspect 3 statues enabled.',
    'inspect 3 statues selected.',
    'inspection interrupted.',
    'interrupted speaker.',
    'left alone while attempting banana bread.',
    'left statue inspected.',
    'marked book.',
    'marked less suspicious.',
    'marked neutral suspicion.',
    'marked spy less suspicious.',
    'marked spy neutral suspicion.',
    'marked spy suspicious.',
    'marked suspicious.',
    'missions completed successfully.',
    'missions completed. 10 second countdown.',
    'missions completed. countdown pending.',
    'overtime!',
    'picked up fingerprintable briefcase (difficult).',
    'picked up fingerprintable briefcase.',
    'picked up fingerprintable statue (difficult).',
    'picked up fingerprintable statue.',
    'picked up statue.',
    'purloin guest list aborted.',
    'purloin guest list enabled.',
    'purloin guest list selected.',
    'put back statue.',
    'put book in bookcase.',
    'read book.',
    'real banana bread started.',
    'rejected cupcake from bartender.',
    'rejected cupcake from waiter.',
    'rejected drink from bartender.',
    'rejected drink from waiter.',
    'remove microfilm from book.',
    'request cupcake from bartender.',
    'request cupcake from waiter.',
    'request drink from bartender.',
    'request drink from waiter.',
    'right statue inspected.',
    'seduce target enabled.',
    'seduce target selected.',
    'seduction canceled.',
    'seduction target cast.',
    'sipped drink.',
    'sniper shot civilian.',
    'sniper shot spy.',
    'sniper shot too late for sync.',
    'spy cast.',
    'spy enters conversation.',
    'spy joined conversation with double agent.',
    'spy leaves conversation.',
    'spy left conversation with double agent.',
    'spy picks up briefcase.',
    'spy player takes control from ai.',
    'spy puts down briefcase.',
    'spy ran out of time.',
    'spy returns briefcase.',
    'started fingerprinting book.',
    'started fingerprinting briefcase.',
    'started fingerprinting cupcake.',
    'started fingerprinting drink.',
    'started fingerprinting statue.',
    'started talking.',
    'statue inspection interrupted.',
    'statue swap pending.',
    'statue swapped.',
    'stopped talking.',
    'suspected double agent cast.',
    'swap statue enabled.',
    'swap statue selected.',
    'target seduced.',
    'took last bite of cupcake.',
    'took last sip of drink.',
    'took shot.',
    'transfer microfilm enabled.',
    'transfer microfilm selected.',
    'transferred microfilm.',
    'waiter gave up.',
    'waiter offered cupcake.',
    'waiter offered drink.',
    'waiter stopped offering cupcake.',
    'waiter stopped offering drink.',
    'watch checked to add time.',
    'watch checked.'
)

def search_events(*terms):
    for ev in all_unique_timeline_events:
        for term in terms:
            if term in ev:
                print(ev)
                break
