
venues = {
    'Balcony',
    'Moderne',
    'Teien',
    'High-Rise',
    'Pub',
    'Gallery',
    'Ballroom',
    'Courtyard',
    'Terrace',
    'Veranda',
    'Aquarium',
    'Library',
    'Redwoods'
}

bar_venues = {
    'Moderne',
    'Pub',
    'Terrace',
    'Aquarium',
    'Redwoods'
}
tray_venues = venues - bar_venues

hva_venues = {
    'Aquarium',
    'Balcony',
    'Courtyard',
    'Pub',
    'Gallery',
    'Terrace',
    'Library'
}
lva_venues = venues - hva_venues

full_inspect_venues = {
    'Ballroom',
    'Courtyard',
    'High-Rise',
    'Library',
    'Pub',
    'Teien',
}
partial_inspect_venues = {
    'Aquarium',
    'High-Rise',
    'Moderne',
    'Redwoods',
    'Terrace',
    'Veranda',
}
statue_venues = partial_inspect_venues | full_inspect_venues

bookshelf_venues = {
    'Aquarium',
    'Ballroom',
    'Gallery',
    'High-Rise',
    'Library',
    'Moderne',
    'Redwoods',
    'Teien',
    'Veranda',
}
bookless_venues = venues - bookshelf_venues

# tuple-indexed dictionary ("venue", "value")
venue_information = {
    ('Balcony', 'SuspectedDoubleAgents'): 0,
    ('Courtyard', 'SuspectedDoubleAgents'): 2,
    ('Teien', 'SuspectedDoubleAgents'): 2,
    ('Gallery', 'SuspectedDoubleAgents'): 2,
    ('Terrace', 'SuspectedDoubleAgents'): 1,
    ('Aquarium', 'SuspectedDoubleAgents'): 2,
    ('Veranda', 'SuspectedDoubleAgents'): 3,
    ('Library', 'SuspectedDoubleAgents'): 3,
    ('High-Rise', 'SuspectedDoubleAgents'): 2,
    ('Redwoods', 'SuspectedDoubleAgents'): 2,
    ('Ballroom', 'SuspectedDoubleAgents'): 2,
    ('Pub', 'SuspectedDoubleAgents'): 2,
    ('Moderne', 'SuspectedDoubleAgents'): 3,

    ('Balcony', 'Statues'): 0,
    ('Balcony', 'Bookshelves'): 0,
    ('Balcony', 'Conversations'): 1,
    ('Balcony', 'Paintings'): 0,
    ('Balcony', 'Windows'): 2,
    ('Courtyard', 'Statues'): 4,
    ('Courtyard', 'Bookshelves'): 0,
    ('Courtyard', 'Conversations'): 4,
    ('Courtyard', 'Paintings'): 0,
    ('Courtyard', 'Windows'): 4,
    ('Teien', 'Statues'): 6,
    ('Teien', 'Bookshelves'): 2,
    ('Teien', 'Conversations'): 2,
    ('Teien', 'Paintings'): 0,
    ('Teien', 'Windows'): 5,
    ('Gallery', 'Statues'): 4,
    ('Gallery', 'Bookshelves'): 2,
    ('Gallery', 'Conversations'): 2,
    ('Gallery', 'Paintings'): 8,
    ('Gallery', 'Windows'): 2,
    ('Terrace', 'Statues'): 4,
    ('Terrace', 'Bookshelves'): 0,
    ('Terrace', 'Conversations'): 2,
    ('Terrace', 'Paintings'): 0,
    ('Terrace', 'Windows'): 3,
    ('Aquarium', 'Statues'): 8,
    ('Aquarium', 'Bookshelves'): 2,
    ('Aquarium', 'Conversations'): 3,
    ('Aquarium', 'Paintings'): 0,
    ('Aquarium', 'Windows'): 5,
    ('Veranda', 'Statues'): 8,
    ('Veranda', 'Bookshelves'): 3,
    ('Veranda', 'Conversations'): 5,
    ('Veranda', 'Paintings'): 0,
    ('Veranda', 'Windows'): 7,
    ('Library', 'Statues'): 6,
    ('Library', 'Bookshelves'): 3,
    ('Library', 'Conversations'): 4,
    ('Library', 'Paintings'): 3,
    ('Library', 'Windows'): 4,
    ('High-Rise', 'Statues'): 7,
    ('High-Rise', 'Bookshelves'): 2,
    ('High-Rise', 'Conversations'): 2,
    ('High-Rise', 'Paintings'): 1,
    ('High-Rise', 'Windows'): 3,
    ('Redwoods', 'Statues'): 6,
    ('Redwoods', 'Bookshelves'): 3,
    ('Redwoods', 'Conversations'): 3,
    ('Redwoods', 'Paintings'): 0,
    ('Redwoods', 'Windows'): 5,
    ('Ballroom', 'Statues'): 6,
    ('Ballroom', 'Bookshelves'): 2,
    ('Ballroom', 'Conversations'): 5,
    ('Ballroom', 'Paintings'): 3,
    ('Ballroom', 'Windows'): 6,
    ('Pub', 'Statues'): 2,
    ('Pub', 'Bookshelves'): 0,
    ('Pub', 'Conversations'): 4,
    ('Pub', 'Paintings'): 0,
    ('Pub', 'Windows'): 3,
    ('Moderne', 'Statues'): 6,
    ('Moderne', 'Bookshelves'): 3,
    ('Moderne', 'Conversations'): 4,
    ('Moderne', 'Paintings'): 0,
    ('Moderne', 'Windows'): 3,

    ('Balcony', 'Inspects'): 0,
    ('Courtyard', 'Inspects'): 2,
    ('Teien', 'Inspects'): 3,
    ('Gallery', 'Inspects'): 3,
    ('Terrace', 'Inspects'): 3,
    ('Aquarium', 'Inspects'): 3,
    ('Veranda', 'Inspects'): 3,
    ('Library', 'Inspects'): 3,
    ('High-Rise', 'Inspects'): 3,
    ('Redwoods', 'Inspects'): 3,
    ('Ballroom', 'Inspects'): 3,
    ('Pub', 'Inspects'): 1,
    ('Moderne', 'Inspects'): 3
}